const Arrayobj = [
    {
        name: "Tata Tea Chakra Gold Premium Leaf Tea",
        image: "https://m.media-amazon.com/images/I/61cVbY5WeZL._AC_UL480_FMwebp_QL65_.jpg",
        price: 250,
        quantity: 20,
        measure: "kg",
        order: 0,
        cart: 0,
        extra: {
            price:0,
            quantity:0
        },
    },
    {
        name: "Aroma Elanchi Soan Papdi-Made with Finest",
        image: "https://m.media-amazon.com/images/I/513P2XYMuUL._AC_UL480_FMwebp_QL65_.jpg",
        price: 150,
        quantity: 10,
        measure: "kg",
        order: 0,
        cart: 0,
    },
    {
        name: "Amazon Brand - Solimo Fresh Dates 500g",
        image: "https://m.media-amazon.com/images/I/817o567rioL._AC_UL480_FMwebp_QL65_.jpg",
        price: 120,
        quantity: 0.5,
        measure: "kg",
        order: 0,
        cart: 0,
    },
    {
        name: "Fresh Eggs",
        image: "https://m.media-amazon.com/images/I/31tbuj9qMgL._AC_UL480_FMwebp_QL65_.jpg",
        price: 80,
        quantity: 12,
        measure: "pcs",
        order: 0,
        cart: 0,
    },
    {
        name: "Amazon Brand - Vedaka Foxnuts (Phool Makhana)",
        image: "https://m.media-amazon.com/images/I/81hT2+8VYWL._AC_UL480_FMwebp_QL65_.jpg",
        price: 200,
        quantity: 0.5,
        measure: "kg",
        order: 0,
        cart: 0,
    },
    {
        name: "Taj Mahal South Tea 500 g Pack",
        image: "https://m.media-amazon.com/images/I/61F1rdVUddL._AC_UL480_FMwebp_QL65_.jpg",
        price: 180,
        quantity: 0.5,
        measure: "kg",
        order: 0,
        cart: 0,
    },
    {
        name: "Dabur Organic Honey – 500g",
        image: "https://m.media-amazon.com/images/I/71OJ0TaSfjL._AC_UL480_FMwebp_QL65_.jpg",
        price: 300,
        quantity: 0.5,
        measure: "kg",
        order: 0,
        cart: 0,
    },
    {
        name: "Dove Deeply Nourishing Body Wash",
        image: "https://m.media-amazon.com/images/I/419w4PBH11L._AC_UL480_FMwebp_QL65_.jpg",
        price: 150,
        quantity: 500,
        measure: "ml",
        order: 0,
        cart: 0,
    },
    {
        name: "Happilo 100% Natural Premium California Almonds 1kg Value Pack Pouch",
        image: "https://m.media-amazon.com/images/I/713D1eLsaqL._AC_UL480_FMwebp_QL65_.jpg",
        price: 500,
        quantity: 1,
        measure: "kg",
        order: 0,
        cart: 0,
    },
    {
        name: "Daawat Super Basmati Rice 1Kg",
        image: "https://m.media-amazon.com/images/I/619QL7kXPFL._AC_UL480_FMwebp_QL65_.jpg",
        price: 150,
        quantity: 1,
        measure: "kg",
        order: 0,
        cart: 0,
    },
    {
        name: "Pure Tree Certified Organic Jeera Powder",
        image: "https://m.media-amazon.com/images/I/71hI7t9OG3L._AC_UL480_FMwebp_QL65_.jpg",
        price: 100,
        quantity: 200,
        measure: "g",
        order: 0,
        cart: 0,
    },
    {
        name: "KING SOLOMON DATES Large Medjoul/Medjool Dates 1 Kg|All Natural",
        image: "https://m.media-amazon.com/images/I/61Y2riTHHrL._AC_UL480_FMwebp_QL65_.jpg",
        price: 300,
        quantity: 1,
        measure: "kg",
        order: 0,
        cart: 0,
    },
    {
        name: "Kellogg's Special K Original with Whole Wheat",
        image: "https://m.media-amazon.com/images/I/61-BUCkRsKL._AC_UL480_QL65_.jpg",
        price: 200,
        quantity: 500,
        measure: "g",
        order: 0,
        cart: 0,
    },
    {
        name: "NUTRI BINGE 100% Natural Whole Cashews",
        image: "https://m.media-amazon.com/images/I/61mZPXS3alL._AC_UL480_QL65_.jpg",
        price: 280,
        quantity: 500,
        measure: "g",
        order: 0,
        cart: 0,
    },
    {
        name: "Amazon Brand - Vedaka Cold Pressed Sesame (Gingelly) Oil",
        image: "https://m.media-amazon.com/images/I/81A2sRIy4zL._AC_UL480_QL65_.jpg",
        price: 220,
        quantity: 500,
        measure: "ml",
        order: 0,
        cart: 0,
    },
    {
        name: "Amazon Brand - Vedaka Premium-Quality Jaggery Powder",
        image: "https://m.media-amazon.com/images/I/81cgKFsOngL._AC_UL480_QL65_.jpg",
        price: 150,
        quantity: 1,
        measure: "kg",
        order: 0,
        cart: 0,
    },
    {
        name: "DeHaat Honest Farms Pesticide Free Unpolished Kabuli Chana 1 KG",
        image: "https://m.media-amazon.com/images/I/6127bT6-sSL._AC_UL480_QL65_.jpg",
        price: 200,
        quantity: 1,
        measure: "kg",
        order: 0,
        cart: 0,
    },
    {
        name: "Open Secret Thandai, Milk Beverage",
        image: "https://m.media-amazon.com/images/I/61wk3jrsLCL._AC_UL480_QL65_.jpg",
        price: 120,
        quantity: 1,
        measure: "L",
        order: 0,
        cart: 0,
    },
    {
        name: "Tong Garden Imported - Wasabi Green Peas",
        image: "https://m.media-amazon.com/images/I/61B1y4b5mFL._AC_UL480_QL65_.jpg",
        price: 180,
        quantity: 500,
        measure: "g",
        order: 0,
        cart: 0,
    },
    {
        name: "Tata Salt, 1kg",
        image: "https://m.media-amazon.com/images/I/61-zRoFrfqL._AC_UL480_QL65_.jpg",
        price: 50,
        quantity: 1,
        measure: "kg",
        order: 0,
        cart: 0,
    }
];

export default Arrayobj;